"""project enum updated

Revision ID: ea7ae72b8165
Revises: 3fa66c78471d
Create Date: 2026-06-27 17:57:40.811755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7ae72b8165'
down_revision: Union[str, Sequence[str], None] = '3fa66c78471d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'ANALYZING_CODE'")
    op.execute("ALTER TYPE projectstatus ADD VALUE IF NOT EXISTS 'DEBUGGING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
